/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/session/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Demo Session */
        post: operations["create_demo_session_v1_demo_session__role__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/needs/{need_id}/outcome-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Outcome Preview */
        get: operations["get_outcome_preview_v1_navigator_needs__need_id__outcome_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/needs/{need_id}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Outcome */
        post: operations["post_outcome_v1_navigator_needs__need_id__outcomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/needs/{need_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Navigator Need Workspace */
        get: operations["get_navigator_need_workspace_v1_navigator_needs__need_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/patients/{patient_id}/case": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Navigator Case */
        get: operations["get_navigator_case_v1_navigator_patients__patient_id__case_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/proposed-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Proposed Change */
        post: operations["post_proposed_change_v1_navigator_proposed_changes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/proposed-changes/{proposed_change_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Approval Decision */
        post: operations["post_approval_decision_v1_navigator_proposed_changes__proposed_change_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Navigator Queue */
        get: operations["get_navigator_queue_v1_navigator_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/safety-signals/{signal_id}/acknowledgements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Acknowledgement */
        post: operations["post_acknowledgement_v1_navigator_safety_signals__signal_id__acknowledgements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/safety-signals/{signal_id}/resolutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Resolution */
        post: operations["post_resolution_v1_navigator_safety_signals__signal_id__resolutions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/tasks/{task_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim Task */
        post: operations["claim_task_v1_navigator_tasks__task_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/tasks/{task_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Task */
        post: operations["complete_task_v1_navigator_tasks__task_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/tasks/{task_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Task */
        post: operations["start_task_v1_navigator_tasks__task_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patient/check-ins/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Check In */
        get: operations["get_current_check_in_v1_patient_check_ins_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patient/check-ins/{definition_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Check In */
        post: operations["submit_check_in_v1_patient_check_ins__definition_id__submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patient/check-ins/{submission_id}/fhir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Submission As Synthetic Fhir */
        get: operations["export_submission_as_synthetic_fhir_v1_patient_check_ins__submission_id__fhir_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patient/follow-ups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patient Follow Ups */
        get: operations["get_patient_follow_ups_v1_patient_follow_ups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patient/follow-ups/{request_id}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Follow Up Response */
        post: operations["post_follow_up_response_v1_patient_follow_ups__request_id__responses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patient/journey-timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patient Journey Timeline */
        get: operations["get_patient_journey_timeline_v1_patient_journey_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcknowledgementCreate */
        AcknowledgementCreate: Record<string, never>;
        /** AcknowledgementRead */
        AcknowledgementRead: {
            /**
             * Acknowledged At
             * Format: date-time
             */
            acknowledged_at: string;
            /**
             * Acknowledged By User Id
             * Format: uuid
             */
            acknowledged_by_user_id: string;
            /** Effective State */
            effective_state: string;
            /**
             * Signal Id
             * Format: uuid
             */
            signal_id: string;
        };
        /** AnswerInput */
        AnswerInput: {
            /** Link Id */
            link_id: string;
            /** Value */
            value: string | number | boolean | string[];
        };
        /**
         * ApprovalChangeType
         * @enum {string}
         */
        ApprovalChangeType: "dismiss_signal" | "override_signal_severity" | "authorize_navigation_task" | "authorize_patient_message";
        /** ApprovalDecisionCreate */
        ApprovalDecisionCreate: {
            decision: components["schemas"]["ApprovalDecisionValue"];
            /** Qualifying Role Assignment Id */
            qualifying_role_assignment_id?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** ApprovalDecisionRead */
        ApprovalDecisionRead: {
            /** Applied */
            applied: boolean;
            /**
             * Authorized At
             * Format: date-time
             */
            authorized_at: string;
            /**
             * Authorized By User Id
             * Format: uuid
             */
            authorized_by_user_id: string;
            decision: components["schemas"]["ApprovalDecisionValue"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Proposal State */
            proposal_state: string;
            /**
             * Proposed Change Id
             * Format: uuid
             */
            proposed_change_id: string;
            /**
             * Qualifying Role Assignment Id
             * Format: uuid
             */
            qualifying_role_assignment_id: string;
            qualifying_role_snapshot: components["schemas"]["UserRole"];
            /** Reason */
            reason: string | null;
        };
        /**
         * ApprovalDecisionValue
         * @enum {string}
         */
        ApprovalDecisionValue: "approved" | "declined";
        /** CheckInCorrectedEvent */
        CheckInCorrectedEvent: {
            detail: components["schemas"]["CheckInDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "check_in_corrected";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default check_in_submission
             * @constant
             */
            source_type: "check_in_submission";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /** CheckInDefinitionResponse */
        CheckInDefinitionResponse: {
            /** Active Submission Id */
            active_submission_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Questionnaire Version */
            questionnaire_version: string;
            /** Questions */
            questions: {
                [key: string]: unknown;
            }[];
            /** Title */
            title: string;
        };
        /** CheckInDetail */
        CheckInDetail: {
            /** Correction Of Submission Id */
            correction_of_submission_id: string | null;
            /** Inherited */
            inherited: boolean;
        };
        /** CheckInSubmissionCreate */
        CheckInSubmissionCreate: {
            /** Answers */
            answers: components["schemas"]["AnswerInput"][];
            /** Free Text */
            free_text?: string | null;
            /** Questionnaire Version */
            questionnaire_version: string;
            /** Supersedes Submission Id */
            supersedes_submission_id?: string | null;
        };
        /** CheckInSubmissionErrorDetail */
        CheckInSubmissionErrorDetail: {
            /**
             * Code
             * @enum {string}
             */
            code: "answers_invalid" | "configuration_invalid" | "correction_stale" | "definition_inactive" | "questionnaire_stale";
            /** Message */
            message: string;
        };
        /** CheckInSubmissionErrorResponse */
        CheckInSubmissionErrorResponse: {
            detail: components["schemas"]["CheckInSubmissionErrorDetail"];
        };
        /** CheckInSubmissionResponse */
        CheckInSubmissionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Questionnaire Version */
            questionnaire_version: string;
            /** Status */
            status: string;
            /** Submitted At */
            submitted_at: string;
            /** Supersedes Submission Id */
            supersedes_submission_id: string | null;
        };
        /** CheckInSubmittedEvent */
        CheckInSubmittedEvent: {
            detail: components["schemas"]["CheckInDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "check_in_submitted";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default check_in_submission
             * @constant
             */
            source_type: "check_in_submission";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /** ComparisonDeltaRead */
        ComparisonDeltaRead: {
            /** Current Present */
            current_present: boolean;
            current_value: components["schemas"]["JsonValue"];
            /** Field Identifier */
            field_identifier: string;
            /** Previous Present */
            previous_present: boolean;
            previous_value: components["schemas"]["JsonValue"];
        };
        /**
         * EffectiveProposalState
         * @enum {string}
         */
        EffectiveProposalState: "superseded" | "declined" | "approved" | "pending";
        /** EmptyTaskCommand */
        EmptyTaskCommand: Record<string, never>;
        /** EvidenceRead */
        EvidenceRead: {
            /** Field */
            field: string;
            /** Text */
            text: string;
        };
        /** FollowUpErrorDetail */
        FollowUpErrorDetail: {
            /**
             * Code
             * @enum {string}
             */
            code: "need_closed" | "follow_up_already_answered" | "concurrent_change";
            /** Message */
            message: string;
        };
        /** FollowUpErrorResponse */
        FollowUpErrorResponse: {
            detail: components["schemas"]["FollowUpErrorDetail"];
        };
        /** FollowUpRequestedDetail */
        FollowUpRequestedDetail: {
            /** Prompt */
            prompt: string;
            /** Prompt Version */
            prompt_version: number;
        };
        /** FollowUpRequestedEvent */
        FollowUpRequestedEvent: {
            detail: components["schemas"]["FollowUpRequestedDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "follow_up_requested";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default follow_up_request
             * @constant
             */
            source_type: "follow_up_request";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /** FollowUpRespondedDetail */
        FollowUpRespondedDetail: {
            /** Note */
            note: string | null;
            response: components["schemas"]["FollowUpResponseValue"];
        };
        /** FollowUpRespondedEvent */
        FollowUpRespondedEvent: {
            detail: components["schemas"]["FollowUpRespondedDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "follow_up_responded";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default follow_up_response
             * @constant
             */
            source_type: "follow_up_response";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /** FollowUpResponseCreate */
        FollowUpResponseCreate: {
            /** Note */
            note?: string | null;
            response: components["schemas"]["FollowUpResponseValue"];
        };
        /** FollowUpResponseRead */
        FollowUpResponseRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Note */
            note: string | null;
            /** Replayed */
            replayed: boolean;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            response: components["schemas"]["FollowUpResponseValue"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /**
         * FollowUpResponseValue
         * @enum {string}
         */
        FollowUpResponseValue: "resolved" | "unresolved" | "still_needs_help";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        JsonValue: unknown;
        /** NavigationTaskRead */
        NavigationTaskRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due At */
            due_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Owner Id */
            owner_id: string | null;
            /**
             * Reported Need Id
             * Format: uuid
             */
            reported_need_id: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /**
         * NavigationTaskStatus
         * @enum {string}
         */
        NavigationTaskStatus: "open" | "assigned" | "in_progress" | "completed" | "cancelled";
        /** NavigatorNeedWorkspaceRead */
        NavigatorNeedWorkspaceRead: {
            comparisons: components["schemas"]["WorkspaceComparisonsRead"];
            /** Evidence */
            evidence: components["schemas"]["WorkspaceEvidenceRead"][];
            /** Follow Ups */
            follow_ups: components["schemas"]["WorkspaceFollowUpRead"][];
            need: components["schemas"]["WorkspaceNeedRead"];
            outcome: components["schemas"]["WorkspaceOutcomeRead"] | null;
            /** Tasks */
            tasks: components["schemas"]["WorkspaceTaskRead"][];
            /** Timeline */
            timeline: (components["schemas"]["CheckInSubmittedEvent"] | components["schemas"]["CheckInCorrectedEvent"] | components["schemas"]["NeedReportedEvent"] | components["schemas"]["ProposalCreatedEvent"] | components["schemas"]["ProposalDecidedEvent"] | components["schemas"]["TaskClaimedEvent"] | components["schemas"]["TaskStartedEvent"] | components["schemas"]["TaskCompletedEvent"] | components["schemas"]["FollowUpRequestedEvent"] | components["schemas"]["FollowUpRespondedEvent"] | components["schemas"]["NavigatorOutcomeRecordedEvent"] | components["schemas"]["TaskCancelledEvent"])[];
        };
        /** NavigatorOutcomeDetail */
        NavigatorOutcomeDetail: {
            disposition: components["schemas"]["OutcomeDisposition"];
            /** Note */
            note: string | null;
        };
        /** NavigatorOutcomeRecordedEvent */
        NavigatorOutcomeRecordedEvent: {
            detail: components["schemas"]["NavigatorOutcomeDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "outcome_recorded";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default outcome
             * @constant
             */
            source_type: "outcome";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /** NavigatorQueueRead */
        NavigatorQueueRead: {
            /** Items */
            items: components["schemas"]["QueueItemRead"][];
        };
        /** NeedDetail */
        NeedDetail: {
            /** Inherited */
            inherited: boolean;
            /** Practical Need Label */
            practical_need_label: string;
        };
        /** NeedReportedEvent */
        NeedReportedEvent: {
            detail: components["schemas"]["NeedDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "need_reported";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default reported_need
             * @constant
             */
            source_type: "reported_need";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /** OutcomeCommandCreate */
        OutcomeCommandCreate: {
            disposition: components["schemas"]["OutcomeDisposition"];
            /** Note */
            note?: string | null;
        };
        /** OutcomeCommandRead */
        OutcomeCommandRead: {
            /** Cancelled Task Ids */
            cancelled_task_ids: string[];
            disposition: components["schemas"]["OutcomeDisposition"];
            /**
             * Need Id
             * Format: uuid
             */
            need_id: string;
            /** Note */
            note: string | null;
            /**
             * Outcome Id
             * Format: uuid
             */
            outcome_id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /**
             * Recorded By User Id
             * Format: uuid
             */
            recorded_by_user_id: string;
        };
        /**
         * OutcomeDisposition
         * @enum {string}
         */
        OutcomeDisposition: "resolved" | "closed_unresolved";
        /** OutcomePreviewRead */
        OutcomePreviewRead: {
            /**
             * Need Id
             * Format: uuid
             */
            need_id: string;
            /** Tasks */
            tasks: components["schemas"]["OutcomePreviewTaskRead"][];
        };
        /** OutcomePreviewTaskRead */
        OutcomePreviewTaskRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** PatientCaseRead */
        PatientCaseRead: {
            /** Longitudinal Submissions */
            longitudinal_submissions: components["schemas"]["SubmissionRead"][];
            /** Navigation Tasks */
            navigation_tasks: components["schemas"]["NavigationTaskRead"][];
            /** Open Needs */
            open_needs: components["schemas"]["QueueItemRead"][];
            /** Patient */
            patient: {
                [key: string]: unknown;
            };
            /** Safety Signals */
            safety_signals: components["schemas"]["SafetySignalRead"][];
            /** Upcoming Synthetic Appointment */
            upcoming_synthetic_appointment: {
                [key: string]: unknown;
            } | null;
        };
        /** PatientFollowUpListRead */
        PatientFollowUpListRead: {
            /** Items */
            items: components["schemas"]["PatientFollowUpRead"][];
        };
        /** PatientFollowUpRead */
        PatientFollowUpRead: {
            /**
             * Need Id
             * Format: uuid
             */
            need_id: string;
            /** Note */
            note: string | null;
            /** Prompt */
            prompt: string;
            /** Prompt Version */
            prompt_version: number;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Responded At */
            responded_at: string | null;
            response: components["schemas"]["FollowUpResponseValue"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "awaiting_response" | "answered" | "unavailable_need_closed";
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
        };
        /** PatientOutcomeDetail */
        PatientOutcomeDetail: {
            disposition: components["schemas"]["OutcomeDisposition"];
        };
        /** PatientOutcomeRecordedEvent */
        PatientOutcomeRecordedEvent: {
            detail: components["schemas"]["PatientOutcomeDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "outcome_recorded";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default outcome
             * @constant
             */
            source_type: "outcome";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /** PatientTimelineRead */
        PatientTimelineRead: {
            /** Events */
            events: (components["schemas"]["CheckInSubmittedEvent"] | components["schemas"]["CheckInCorrectedEvent"] | components["schemas"]["NeedReportedEvent"] | components["schemas"]["TaskClaimedEvent"] | components["schemas"]["TaskStartedEvent"] | components["schemas"]["TaskCompletedEvent"] | components["schemas"]["FollowUpRequestedEvent"] | components["schemas"]["FollowUpRespondedEvent"] | components["schemas"]["PatientOutcomeRecordedEvent"] | components["schemas"]["TaskCancelledEvent"])[];
        };
        /** PriorityResultRead */
        PriorityResultRead: {
            /**
             * Level
             * @enum {string}
             */
            level: "high" | "medium" | "routine";
            /** Reasons */
            reasons: string[];
            /** Score */
            score: number;
        };
        /** ProposalCreatedDetail */
        ProposalCreatedDetail: {
            proposal_state: components["schemas"]["EffectiveProposalState"];
            /** Value Schema Id */
            value_schema_id: string;
            /** Value Schema Version */
            value_schema_version: number;
        };
        /** ProposalCreatedEvent */
        ProposalCreatedEvent: {
            detail: components["schemas"]["ProposalCreatedDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "proposal_created";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default proposed_change
             * @constant
             */
            source_type: "proposed_change";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /** ProposalDecidedDetail */
        ProposalDecidedDetail: {
            decision: components["schemas"]["ApprovalDecisionValue"];
        };
        /** ProposalDecidedEvent */
        ProposalDecidedEvent: {
            detail: components["schemas"]["ProposalDecidedDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "proposal_decided";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default approval_decision
             * @constant
             */
            source_type: "approval_decision";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /** ProposedChangeCreate */
        ProposedChangeCreate: {
            change_type: components["schemas"]["ApprovalChangeType"];
            /** Navigation Task Id */
            navigation_task_id?: string | null;
            /** Patient Message Id */
            patient_message_id?: string | null;
            /** Proposed Value */
            proposed_value: {
                [key: string]: unknown;
            };
            /** Rationale */
            rationale: string;
            /** Safety Signal Id */
            safety_signal_id?: string | null;
            /** Supersedes Proposed Change Id */
            supersedes_proposed_change_id?: string | null;
            /** Value Schema Id */
            value_schema_id: string;
            /** Value Schema Version */
            value_schema_version: number;
        };
        /** ProposedChangeRead */
        ProposedChangeRead: {
            /** Allow Self Approval Snapshot */
            allow_self_approval_snapshot: boolean;
            /**
             * Approval Policy Id
             * Format: uuid
             */
            approval_policy_id: string;
            /** Approval Policy Version */
            approval_policy_version: number;
            change_type: components["schemas"]["ApprovalChangeType"];
            deterministic_severity_threshold_snapshot: components["schemas"]["SafetySeverity"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Navigation Task Id */
            navigation_task_id: string | null;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Patient Message Id */
            patient_message_id: string | null;
            /**
             * Proposed At
             * Format: date-time
             */
            proposed_at: string;
            /** Proposed By User Id */
            proposed_by_user_id: string | null;
            /** Proposed Value */
            proposed_value: {
                [key: string]: unknown;
            };
            /** Rationale */
            rationale: string;
            /** Required Approval Count Snapshot */
            required_approval_count_snapshot: number;
            required_approver_role_snapshot: components["schemas"]["UserRole"];
            /** Safety Signal Id */
            safety_signal_id: string | null;
            /** State */
            state: string;
            /** Supersedes Proposed Change Id */
            supersedes_proposed_change_id: string | null;
            /** Value Schema Id */
            value_schema_id: string;
            /** Value Schema Version */
            value_schema_version: number;
        };
        /** QueueItemRead */
        QueueItemRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due At */
            due_at: string | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRead"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "symptom_change" | "medication_question" | "transportation" | "financial_support" | "other";
            /**
             * Need Id
             * Format: uuid
             */
            need_id: string;
            /** Owner Id */
            owner_id: string | null;
            /** Patient Display Name */
            patient_display_name: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            priority: components["schemas"]["PriorityResultRead"];
        };
        /** ResolutionCreate */
        ResolutionCreate: {
            /** Resolution Reason */
            resolution_reason: string;
        };
        /** ResolutionRead */
        ResolutionRead: {
            /** Effective State */
            effective_state: string;
            /**
             * Resolution Id
             * Format: uuid
             */
            resolution_id: string;
            /** Resolution Reason */
            resolution_reason: string;
            /**
             * Resolved At
             * Format: date-time
             */
            resolved_at: string;
            /**
             * Resolved By User Id
             * Format: uuid
             */
            resolved_by_user_id: string;
            /**
             * Signal Id
             * Format: uuid
             */
            signal_id: string;
        };
        /**
         * SafetySeverity
         * @enum {string}
         */
        SafetySeverity: "routine" | "urgent" | "emergent";
        /** SafetySignalRead */
        SafetySignalRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRead"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rule Code */
            rule_code: string;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
        };
        /** SubmissionComparisonRead */
        SubmissionComparisonRead: {
            /** Current Submission Id */
            current_submission_id?: string | null;
            /** Deltas */
            deltas?: components["schemas"]["ComparisonDeltaRead"][];
            /** Label */
            label: string;
            /** Previous Submission Id */
            previous_submission_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "insufficient_history" | "not_comparable";
        };
        /** SubmissionRead */
        SubmissionRead: {
            /** Free Text */
            free_text: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /** Submitted At */
            submitted_at: string | null;
        };
        /** TaskCancelledDetail */
        TaskCancelledDetail: {
            /**
             * Reason
             * @constant
             */
            reason: "need_closed";
        };
        /** TaskCancelledEvent */
        TaskCancelledEvent: {
            detail: components["schemas"]["TaskCancelledDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "task_cancelled";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default audit_event
             * @constant
             */
            source_type: "audit_event";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /** TaskClaimCreate */
        TaskClaimCreate: {
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /**
             * Proposed Change Id
             * Format: uuid
             */
            proposed_change_id: string;
        };
        /** TaskClaimedEvent */
        TaskClaimedEvent: {
            detail: components["schemas"]["TaskProgressDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "task_claimed";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default audit_event
             * @constant
             */
            source_type: "audit_event";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /** TaskCommandErrorDetail */
        TaskCommandErrorDetail: {
            /**
             * Code
             * @enum {string}
             */
            code: "need_closed" | "task_state_conflict" | "task_claim_mismatch" | "task_unbound" | "proposal_not_approved" | "concurrent_change";
            /** Message */
            message: string;
        };
        /** TaskCommandErrorResponse */
        TaskCommandErrorResponse: {
            detail: components["schemas"]["TaskCommandErrorDetail"];
        };
        /** TaskCommandRead */
        TaskCommandRead: {
            /** Assignee User Id */
            assignee_user_id: string | null;
            /** Authorized Proposed Change Id */
            authorized_proposed_change_id: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Due At */
            due_at: string | null;
            /** Follow Up Request Id */
            follow_up_request_id: string | null;
            /**
             * Need Id
             * Format: uuid
             */
            need_id: string;
            /** Replayed */
            replayed: boolean;
            status: components["schemas"]["NavigationTaskStatus"];
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
        };
        /** TaskCompletedEvent */
        TaskCompletedEvent: {
            detail: components["schemas"]["TaskProgressDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "task_completed";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default audit_event
             * @constant
             */
            source_type: "audit_event";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /** TaskProgressDetail */
        TaskProgressDetail: {
            /**
             * Status
             * @enum {string}
             */
            status: "assigned" | "in_progress" | "completed";
        };
        /** TaskStartedEvent */
        TaskStartedEvent: {
            detail: components["schemas"]["TaskProgressDetail"];
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "task_started";
            /** Need Id */
            need_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Source Type
             * @default audit_event
             * @constant
             */
            source_type: "audit_event";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "administrator" | "navigator" | "supporting_actor";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceApprovalDecisionRead */
        WorkspaceApprovalDecisionRead: {
            /**
             * Authorized At
             * Format: date-time
             */
            authorized_at: string;
            /**
             * Authorized By User Id
             * Format: uuid
             */
            authorized_by_user_id: string;
            /** Decision */
            decision: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Qualifying Role Assignment Id
             * Format: uuid
             */
            qualifying_role_assignment_id: string;
            /** Qualifying Role Snapshot */
            qualifying_role_snapshot: string;
            /** Reason */
            reason: string | null;
        };
        /** WorkspaceApprovalPolicyRead */
        WorkspaceApprovalPolicyRead: {
            /** Allow Self Approval */
            allow_self_approval: boolean;
            /** Deterministic Severity Threshold */
            deterministic_severity_threshold: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Required Approval Count */
            required_approval_count: number;
            /** Required Approver Role */
            required_approver_role: string;
            /** Version */
            version: number;
        };
        /** WorkspaceComparisonsRead */
        WorkspaceComparisonsRead: {
            between_check_ins: components["schemas"]["SubmissionComparisonRead"];
            correction: components["schemas"]["SubmissionComparisonRead"];
        };
        /** WorkspaceEvidenceRead */
        WorkspaceEvidenceRead: {
            /** Display Text */
            display_text: string;
            /** Field Identifier */
            field_identifier: string;
            /**
             * Provenance Kind
             * @enum {string}
             */
            provenance_kind: "source_submission" | "inherited_history" | "stored_need_evidence";
            /** Source Submission Id */
            source_submission_id: string | null;
            value: components["schemas"]["JsonValue"];
            /** Value Present */
            value_present: boolean;
        };
        /** WorkspaceFollowUpRead */
        WorkspaceFollowUpRead: {
            /**
             * Navigation Task Id
             * Format: uuid
             */
            navigation_task_id: string;
            /** Prompt Version */
            prompt_version: number;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /**
             * Requested By User Id
             * Format: uuid
             */
            requested_by_user_id: string;
            /** Responded At */
            responded_at: string | null;
            /** Response */
            response: string | null;
            /** Response Note */
            response_note: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "awaiting_response" | "answered" | "unavailable_need_closed";
        };
        /** WorkspaceNeedRead */
        WorkspaceNeedRead: {
            /**
             * Care Episode Id
             * Format: uuid
             */
            care_episode_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Effective State */
            effective_state: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Patient Display Name */
            patient_display_name: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /** Raw Status */
            raw_status: string;
            /** Reopened From Need Id */
            reopened_from_need_id: string | null;
        };
        /** WorkspaceOutcomeRead */
        WorkspaceOutcomeRead: {
            /** Disposition */
            disposition: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Note */
            note: string | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /**
             * Recorded By User Id
             * Format: uuid
             */
            recorded_by_user_id: string;
        };
        /** WorkspaceProposalRead */
        WorkspaceProposalRead: {
            /** Change Type */
            change_type: string;
            /** Decisions */
            decisions: components["schemas"]["WorkspaceApprovalDecisionRead"][];
            /** Execution Authorized */
            execution_authorized: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            policy: components["schemas"]["WorkspaceApprovalPolicyRead"];
            /**
             * Proposed At
             * Format: date-time
             */
            proposed_at: string;
            /** Proposed Value */
            proposed_value: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Rationale */
            rationale: string;
            /** Resources */
            resources: components["schemas"]["WorkspaceResourceRead"][];
            /** Reviewable */
            reviewable: boolean;
            /**
             * Root Proposal Id
             * Format: uuid
             */
            root_proposal_id: string;
            /** State */
            state: string;
            /** Supersedes Proposed Change Id */
            supersedes_proposed_change_id: string | null;
            /** Supported */
            supported: boolean;
            /** Title */
            title: string | null;
            /** Unsupported Reason */
            unsupported_reason: string | null;
            /** Value Schema Id */
            value_schema_id: string;
            /** Value Schema Version */
            value_schema_version: number;
        };
        /** WorkspaceResourceRead */
        WorkspaceResourceRead: {
            /** Approved At */
            approved_at: string | null;
            /** Category */
            category: string;
            /** Delivered At */
            delivered_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Match Rationale */
            match_rationale: string;
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Name */
            name: string;
            /**
             * Proposed At
             * Format: date-time
             */
            proposed_at: string;
            /**
             * Resource Id
             * Format: uuid
             */
            resource_id: string;
            /** Url */
            url: string | null;
        };
        /** WorkspaceTaskRead */
        WorkspaceTaskRead: {
            /** Assignee User Id */
            assignee_user_id: string | null;
            /** Authorized Proposed Change Id */
            authorized_proposed_change_id: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due At */
            due_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Proposals */
            proposals: components["schemas"]["WorkspaceProposalRead"][];
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_demo_session_v1_demo_session__role__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: components["schemas"]["UserRole"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outcome_preview_v1_navigator_needs__need_id__outcome_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                need_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomePreviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_outcome_v1_navigator_needs__need_id__outcomes_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                need_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeCommandCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeCommandRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_navigator_need_workspace_v1_navigator_needs__need_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                need_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigatorNeedWorkspaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_navigator_case_v1_navigator_patients__patient_id__case_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_proposed_change_v1_navigator_proposed_changes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposedChangeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposedChangeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_approval_decision_v1_navigator_proposed_changes__proposed_change_id__decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposed_change_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDecisionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_navigator_queue_v1_navigator_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigatorQueueRead"];
                };
            };
        };
    };
    post_acknowledgement_v1_navigator_safety_signals__signal_id__acknowledgements_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcknowledgementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_resolution_v1_navigator_safety_signals__signal_id__resolutions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolutionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolutionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_task_v1_navigator_tasks__task_id__claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskClaimCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCommandRead"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCommandErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_task_v1_navigator_tasks__task_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyTaskCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCommandRead"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCommandErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_task_v1_navigator_tasks__task_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyTaskCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCommandRead"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCommandErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_check_in_v1_patient_check_ins_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInDefinitionResponse"];
                };
            };
        };
    };
    submit_check_in_v1_patient_check_ins__definition_id__submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                definition_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInSubmissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInSubmissionResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInSubmissionErrorResponse"];
                };
            };
        };
    };
    export_submission_as_synthetic_fhir_v1_patient_check_ins__submission_id__fhir_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_follow_ups_v1_patient_follow_ups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientFollowUpListRead"];
                };
            };
        };
    };
    post_follow_up_response_v1_patient_follow_ups__request_id__responses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowUpResponseCreate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUpResponseRead"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUpResponseRead"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUpErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_journey_timeline_v1_patient_journey_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientTimelineRead"];
                };
            };
        };
    };
}
