/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/session/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Demo Session */
        post: operations["create_demo_session_v1_demo_session__role__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/needs/{need_id}/outcome-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Outcome Preview */
        get: operations["get_outcome_preview_v1_navigator_needs__need_id__outcome_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/needs/{need_id}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Outcome */
        post: operations["post_outcome_v1_navigator_needs__need_id__outcomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/patients/{patient_id}/case": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Navigator Case */
        get: operations["get_navigator_case_v1_navigator_patients__patient_id__case_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/proposed-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Proposed Change */
        post: operations["post_proposed_change_v1_navigator_proposed_changes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/proposed-changes/{proposed_change_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Approval Decision */
        post: operations["post_approval_decision_v1_navigator_proposed_changes__proposed_change_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Navigator Queue */
        get: operations["get_navigator_queue_v1_navigator_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/safety-signals/{signal_id}/acknowledgements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Acknowledgement */
        post: operations["post_acknowledgement_v1_navigator_safety_signals__signal_id__acknowledgements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/navigator/safety-signals/{signal_id}/resolutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Resolution */
        post: operations["post_resolution_v1_navigator_safety_signals__signal_id__resolutions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patient/check-ins/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Check In */
        get: operations["get_current_check_in_v1_patient_check_ins_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patient/check-ins/{definition_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Check In */
        post: operations["submit_check_in_v1_patient_check_ins__definition_id__submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patient/check-ins/{submission_id}/fhir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Submission As Synthetic Fhir */
        get: operations["export_submission_as_synthetic_fhir_v1_patient_check_ins__submission_id__fhir_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcknowledgementCreate */
        AcknowledgementCreate: Record<string, never>;
        /** AcknowledgementRead */
        AcknowledgementRead: {
            /**
             * Acknowledged At
             * Format: date-time
             */
            acknowledged_at: string;
            /**
             * Acknowledged By User Id
             * Format: uuid
             */
            acknowledged_by_user_id: string;
            /** Effective State */
            effective_state: string;
            /**
             * Signal Id
             * Format: uuid
             */
            signal_id: string;
        };
        /** AnswerInput */
        AnswerInput: {
            /** Link Id */
            link_id: string;
            /** Value */
            value: string | number | boolean | string[];
        };
        /**
         * ApprovalChangeType
         * @enum {string}
         */
        ApprovalChangeType: "dismiss_signal" | "override_signal_severity" | "authorize_navigation_task" | "authorize_patient_message";
        /** ApprovalDecisionCreate */
        ApprovalDecisionCreate: {
            decision: components["schemas"]["ApprovalDecisionValue"];
            /**
             * Qualifying Role Assignment Id
             * Format: uuid
             */
            qualifying_role_assignment_id: string;
            /** Reason */
            reason?: string | null;
        };
        /** ApprovalDecisionRead */
        ApprovalDecisionRead: {
            /** Applied */
            applied: boolean;
            /**
             * Authorized At
             * Format: date-time
             */
            authorized_at: string;
            /**
             * Authorized By User Id
             * Format: uuid
             */
            authorized_by_user_id: string;
            decision: components["schemas"]["ApprovalDecisionValue"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Proposal State */
            proposal_state: string;
            /**
             * Proposed Change Id
             * Format: uuid
             */
            proposed_change_id: string;
            /**
             * Qualifying Role Assignment Id
             * Format: uuid
             */
            qualifying_role_assignment_id: string;
            qualifying_role_snapshot: components["schemas"]["UserRole"];
            /** Reason */
            reason: string | null;
        };
        /**
         * ApprovalDecisionValue
         * @enum {string}
         */
        ApprovalDecisionValue: "approved" | "declined";
        /** CheckInDefinitionResponse */
        CheckInDefinitionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Questionnaire Version */
            questionnaire_version: string;
            /** Questions */
            questions: {
                [key: string]: unknown;
            }[];
            /** Title */
            title: string;
        };
        /** CheckInSubmissionCreate */
        CheckInSubmissionCreate: {
            /** Answers */
            answers: components["schemas"]["AnswerInput"][];
            /** Free Text */
            free_text?: string | null;
            /** Questionnaire Version */
            questionnaire_version: string;
        };
        /** CheckInSubmissionResponse */
        CheckInSubmissionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Questionnaire Version */
            questionnaire_version: string;
            /** Status */
            status: string;
            /** Submitted At */
            submitted_at: string;
        };
        /** EvidenceRead */
        EvidenceRead: {
            /** Field */
            field: string;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NavigationTaskRead */
        NavigationTaskRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due At */
            due_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Owner Id */
            owner_id: string | null;
            /**
             * Reported Need Id
             * Format: uuid
             */
            reported_need_id: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** NavigatorQueueRead */
        NavigatorQueueRead: {
            /** Items */
            items: components["schemas"]["QueueItemRead"][];
        };
        /** OutcomeCommandCreate */
        OutcomeCommandCreate: {
            disposition: components["schemas"]["OutcomeDisposition"];
            /** Note */
            note?: string | null;
        };
        /** OutcomeCommandRead */
        OutcomeCommandRead: {
            /** Cancelled Task Ids */
            cancelled_task_ids: string[];
            disposition: components["schemas"]["OutcomeDisposition"];
            /**
             * Need Id
             * Format: uuid
             */
            need_id: string;
            /** Note */
            note: string | null;
            /**
             * Outcome Id
             * Format: uuid
             */
            outcome_id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /**
             * Recorded By User Id
             * Format: uuid
             */
            recorded_by_user_id: string;
        };
        /**
         * OutcomeDisposition
         * @enum {string}
         */
        OutcomeDisposition: "resolved" | "closed_unresolved";
        /** OutcomePreviewRead */
        OutcomePreviewRead: {
            /**
             * Need Id
             * Format: uuid
             */
            need_id: string;
            /** Tasks */
            tasks: components["schemas"]["OutcomePreviewTaskRead"][];
        };
        /** OutcomePreviewTaskRead */
        OutcomePreviewTaskRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** PatientCaseRead */
        PatientCaseRead: {
            /** Longitudinal Submissions */
            longitudinal_submissions: components["schemas"]["SubmissionRead"][];
            /** Navigation Tasks */
            navigation_tasks: components["schemas"]["NavigationTaskRead"][];
            /** Open Needs */
            open_needs: components["schemas"]["QueueItemRead"][];
            /** Patient */
            patient: {
                [key: string]: unknown;
            };
            /** Safety Signals */
            safety_signals: components["schemas"]["SafetySignalRead"][];
            /** Upcoming Synthetic Appointment */
            upcoming_synthetic_appointment: {
                [key: string]: unknown;
            } | null;
        };
        /** PriorityResultRead */
        PriorityResultRead: {
            /**
             * Level
             * @enum {string}
             */
            level: "high" | "medium" | "routine";
            /** Reasons */
            reasons: string[];
            /** Score */
            score: number;
        };
        /** ProposedChangeCreate */
        ProposedChangeCreate: {
            change_type: components["schemas"]["ApprovalChangeType"];
            /** Navigation Task Id */
            navigation_task_id?: string | null;
            /** Patient Message Id */
            patient_message_id?: string | null;
            /** Proposed Value */
            proposed_value: {
                [key: string]: unknown;
            };
            /** Rationale */
            rationale: string;
            /** Safety Signal Id */
            safety_signal_id?: string | null;
            /** Supersedes Proposed Change Id */
            supersedes_proposed_change_id?: string | null;
            /** Value Schema Id */
            value_schema_id: string;
            /** Value Schema Version */
            value_schema_version: number;
        };
        /** ProposedChangeRead */
        ProposedChangeRead: {
            /** Allow Self Approval Snapshot */
            allow_self_approval_snapshot: boolean;
            /**
             * Approval Policy Id
             * Format: uuid
             */
            approval_policy_id: string;
            /** Approval Policy Version */
            approval_policy_version: number;
            change_type: components["schemas"]["ApprovalChangeType"];
            deterministic_severity_threshold_snapshot: components["schemas"]["SafetySeverity"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Navigation Task Id */
            navigation_task_id: string | null;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Patient Message Id */
            patient_message_id: string | null;
            /**
             * Proposed At
             * Format: date-time
             */
            proposed_at: string;
            /** Proposed By User Id */
            proposed_by_user_id: string | null;
            /** Proposed Value */
            proposed_value: {
                [key: string]: unknown;
            };
            /** Rationale */
            rationale: string;
            /** Required Approval Count Snapshot */
            required_approval_count_snapshot: number;
            required_approver_role_snapshot: components["schemas"]["UserRole"];
            /** Safety Signal Id */
            safety_signal_id: string | null;
            /** State */
            state: string;
            /** Supersedes Proposed Change Id */
            supersedes_proposed_change_id: string | null;
            /** Value Schema Id */
            value_schema_id: string;
            /** Value Schema Version */
            value_schema_version: number;
        };
        /** QueueItemRead */
        QueueItemRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due At */
            due_at: string | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRead"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "symptom_change" | "medication_question" | "transportation" | "financial_support" | "other";
            /**
             * Need Id
             * Format: uuid
             */
            need_id: string;
            /** Owner Id */
            owner_id: string | null;
            /** Patient Display Name */
            patient_display_name: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            priority: components["schemas"]["PriorityResultRead"];
        };
        /** ResolutionCreate */
        ResolutionCreate: {
            /** Resolution Reason */
            resolution_reason: string;
        };
        /** ResolutionRead */
        ResolutionRead: {
            /** Effective State */
            effective_state: string;
            /**
             * Resolution Id
             * Format: uuid
             */
            resolution_id: string;
            /** Resolution Reason */
            resolution_reason: string;
            /**
             * Resolved At
             * Format: date-time
             */
            resolved_at: string;
            /**
             * Resolved By User Id
             * Format: uuid
             */
            resolved_by_user_id: string;
            /**
             * Signal Id
             * Format: uuid
             */
            signal_id: string;
        };
        /**
         * SafetySeverity
         * @enum {string}
         */
        SafetySeverity: "routine" | "urgent" | "emergent";
        /** SafetySignalRead */
        SafetySignalRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRead"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rule Code */
            rule_code: string;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
        };
        /** SubmissionRead */
        SubmissionRead: {
            /** Free Text */
            free_text: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /** Submitted At */
            submitted_at: string | null;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "administrator" | "navigator" | "supporting_actor";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_demo_session_v1_demo_session__role__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: components["schemas"]["UserRole"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outcome_preview_v1_navigator_needs__need_id__outcome_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                need_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomePreviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_outcome_v1_navigator_needs__need_id__outcomes_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                need_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeCommandCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeCommandRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_navigator_case_v1_navigator_patients__patient_id__case_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_proposed_change_v1_navigator_proposed_changes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposedChangeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposedChangeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_approval_decision_v1_navigator_proposed_changes__proposed_change_id__decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposed_change_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDecisionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_navigator_queue_v1_navigator_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigatorQueueRead"];
                };
            };
        };
    };
    post_acknowledgement_v1_navigator_safety_signals__signal_id__acknowledgements_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcknowledgementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_resolution_v1_navigator_safety_signals__signal_id__resolutions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolutionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolutionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_check_in_v1_patient_check_ins_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInDefinitionResponse"];
                };
            };
        };
    };
    submit_check_in_v1_patient_check_ins__definition_id__submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                definition_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInSubmissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInSubmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_submission_as_synthetic_fhir_v1_patient_check_ins__submission_id__fhir_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
